### ISSUE TITLE
[Feature] Skip web hook enabled modules in bot

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#10]
This is an outgrowth of https://github.com/KSP-CKAN/CKAN/issues/2789#issuecomment-506253256. I assume that the initial functionality of the queue-based bot will be identical to NetKAN-bot, so ideas for further improvements should be submitted here for better tracking.

## Motivation

If a mod's `$kref` is on SpaceDock, our web hook will be notified of new uploads immediately, making the bot redundant some of the time. If a mod has a `$vref` property, then it's still necessary to crawl it, as its KSP-AVC version file may have a `"URL"` property pointing to a supplemental remote version file that could be changed at any time without notifying any web hook. But if there is no `$vref`, then the web hook should be sufficient by itself.

## Suggestion

If a module has a SpaceDock `$kref` and **no** `$vref`, it doesn't need to be added to the queue for inflation. Skip it.

There are 789 such modules, or about a third of the total, so this could cut the bot's total CPU load significantly.

**Comment by techman83** [comment]
I like this idea!
