### ISSUE TITLE
[Bug] Problems with queue param of Mirrorer

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#128]
## Problems

#126 moved the `queue` param of `Mirrorer.process_queue` into the constructor.

https://github.com/KSP-CKAN/NetKAN-Infra/blob/3c64accf0eb10c14c3ef304908cbf123b87d7c5d/netkan/netkan/mirrorer.py#L20

- This is only needed by `process_queue`
- `cli.mirror_purge_epochs` doesn't pass it and so doesn't work

https://github.com/KSP-CKAN/NetKAN-Infra/blob/3c64accf0eb10c14c3ef304908cbf123b87d7c5d/netkan/netkan/cli.py#L394-L399

## Suggestions

Move the `queue` param back to `Mirrorer.process_queue`.

**Comment by techman83** [comment]
I'm going to have a good look at the purge epoch function. I'm really in favour of keeping the queue as part of the class, so all queue based classes can inherit from the same base. But there is some python stuff we can lean on so that we can do this without adding it as an arg on 'process_queue'.
