### ISSUE TITLE
[Bug] Mirrorer only Checks Item, not files

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#131]
Problem
-------
There is an implementation change between the legacy mirroring and the new mirroring:

https://github.com/KSP-CKAN/NetKAN-bot/blob/master/lib/App/KSP_CKAN/Tools/IA.pm#L268

The perl method checks to see if the SHA1s of the files match before considering it mirrored.
```perl
  if ( any { defined $_->{sha1} && uc($_->{sha1}) eq $ckan->download_sha1 } @{$data->{files}} ) {
    return 1;
  }

  return 0;
```

However the new service only checks to see if the item exists:
```python
    def mirrored(self, iarchive):
        results = iarchive.search_items(self.mirror_item())
        return True if results else False
```

Files can change and be the same version or a file upload may not complete and we could miss retrying later.

Recommendation
-------
Ensure we check all the files to see if we have a matching SHA1. Though I'm in favour of switching to a different algorithm if better ones are available via the IA metadata now.

**Comment by HebaruSan** [comment]
> Though I'm in favour of switching to a different algorithm if better ones are available via the IA metadata now.

Looks like our options are MD5, SHA1, and CRC32. So, nothing from this century.
https://archive.org/services/docs/api/metadata-schema/index.html#file-metadata-schema

**Comment by techman83** [comment]
SHA1 is probably the pick of the bunch still.

**Comment by HebaruSan** [comment]
... I'm not seeing how to get from the search results to the files. The documentation isn't very complete, they like to not define the properties that are available on their objects.

**Comment by techman83** [comment]
We actually don't use the search interface in the old code, we query the item directly, which returns it and files are included. But I've not looked hard at the python library for the IA, all the perl stuff was custom written.

This is an excerpt of part of what we expected from the api:

```json
{ "files": [ { "name": "74770739-ExampleKAN-1.0.0.1.zip", "sha1": "1a2B3c4D5e"} ] }
```

**Comment by techman83** [comment]
The get item function will probably do what we want:

```python
In [1]: from internetarchive import get_item                                                                                                                                                                                                                                                                                 

In [2]: item = get_item('EditorExtensionsRedux-3.4.1')                                                                                                                                                                                                                                                                       

In [3]: item.files                                                                                                                                                                                                                                                                                                           
Out[3]: 
[{'name': 'EditorExtensionsRedux-3.4.1_files.xml',
  'source': 'original',
  'format': 'Metadata',
  'md5': 'c9c8a865ec2770fe211fb35176d0a72a'},
 {'name': 'EditorExtensionsRedux-3.4.1_meta.sqlite',
  'source': 'original',
  'mtime': '1580258473',
  'size': '11264',
  'format': 'Metadata',
  'md5': 'e32c26330d0cafd203f4a109356b51f7',
  'crc32': 'cccc2ec8',
  'sha1': 'eef8426f9ba0fef8b76b12c7c13793c5dd22da79'},
 {'name': 'EditorExtensionsRedux-3.4.1_meta.xml',
  'source': 'original',
  'mtime': '1580238850',
  'size': '1177',
  'md5': '96083a15a830ef4047f78533fc7e303e',
  'crc32': 'bec63e96',
  'sha1': 'deee88f2e1472ae865b672f288f2c6d8d56aacec',
  'format': 'Metadata'}]

In [4]: type(item.files)                                                                                                                                                                                                                                                                                                     
Out[4]: list
```

The  get_item function has a `files` property which returns a list. And there looks like a nice `exists` property as well.

```python
In [14]: item.exists                                                                                                                                                                                                                                                                                                         
Out[14]: True
```
