### ISSUE TITLE
[Bug] Mirrorer not re-using cached download from Inflator

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#137]
#133's exception hides a darker truth:

```
  File "/home/netkan/.local/lib/python3.7/site-packages/netkan/mirrorer.py", line 80, in try_mirror
    return self.try_upload(ckan, tmp.file)
```

That code shouldn't be running at all:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/e5fcc09f3cc61cd2c76ac2232b89edff31286596/netkan/netkan/mirrorer.py#L68-L80

1. Inflator runs, downloads file, saves it to the cache (we know this works because Inflator passes now take 10-20 minutes, which would be impossible if it was re-downloading every time)
2. Indexer adds the new .ckan to CKAN-meta
3. Mirrorer runs, checks the cache, the file should be there, and line 68 should find it
4. Instead, line 68 finds nothing, and the `else` block re-downloads the file

I triple checked the logic the Mirrorer uses to check the cache, and it seems solid. The path is right, the glob is right, `Ckan.cache_prefix` is right.

https://github.com/KSP-CKAN/NetKAN-Infra/blob/e5fcc09f3cc61cd2c76ac2232b89edff31286596/netkan/netkan/mirrorer.py#L83-L87

... which leads me to suspect something weird is going on with the way these volumes are shared.

Also the Indexer doesn't use the cache; can we remove this?

https://github.com/KSP-CKAN/NetKAN-Infra/blob/e5fcc09f3cc61cd2c76ac2232b89edff31286596/prod-stack.py#L605-L607

**Comment by HebaruSan** [comment]
Or maybe the Inflator is saving the files to the wrong path?...

**Comment by techman83** [comment]
I don't think this is an issue, the path is available inside the mirrorer and being populated by the inflator.
```
netkan@78e979a83dfa:~$ ls -lah ckan_cache/35013941-NASA-CountDown-1.3.9.1.zip
ls: cannot access 'ckan_cache/35013941-NASA-CountDown-1.3.9.1.zip': No such file or directory
netkan@78e979a83dfa:~$ ls -lah ckan_cache/|grep CountDown
-rw-rw-r-- 1 netkan netkan  3.7M Sep  7 00:51 1CC8D1BF-netkan-LCDLaunchCountDown.zip
-rw-r--r-- 1 netkan netkan   12M Feb  1 03:51 25B8A610-netkan-NASA-CountDown.zip
-rw-r--r-- 1 netkan netkan  3.7M Jan  9 11:24 CEE21E2F-netkan-LCDLaunchCountDown.zip
-rw-r--r-- 1 netkan netkan   12M Jan  9 11:25 FA78F3CE-netkan-NASA-CountDown.zip

```

**Comment by techman83** [comment]
And yes, the indexer doesn't use the download cache, so that is probably just an errant include.

**Comment by HebaruSan** [comment]
`cache_find_file` should be returning the file then. Why wouldn't it?

**Comment by techman83** [comment]
I'd have to dig a little harder than my brief glance, but it would be straight forward enough to write a test case for and go from there.

**Comment by HebaruSan** [comment]
A test will tell us what I've already confirmed, the path is right, the glob is right, `Ckan.cache_prefix` is right. Something's fishy in the environment.

**Comment by techman83** [comment]
Test cases are always useful, it's often when I see where the problem is and helps when refactoring code later and handling library upgrades.

This is the python repl inside the container. It's having no trouble finding the file.
```
>>> from netkan.metadata import Ckan
>>> c = Ckan('/tmp/CKAN-meta/NASA-CountDown/NASA-CountDown-1.3.9.1.ckan')
>>> c.cache_prefix
'1F5A9621'
>>> c.cache_find_file
PosixPath('/home/netkan/ckan_cache/1F5A9621-NASA-CountDown-1.3.9.1.zip')
>>> c.cache_find_file.exists()
True
```

**Comment by HebaruSan** [comment]
That's strange; the three filenames for NASA-CountDown reflect two from the Inflator and one from ckan.exe or the Infra (see KSP-CKAN/CKAN#1637), and **none** of them have matching hashes:

- 25B8A610-netkan-NASA-CountDown.zip
- FA78F3CE-netkan-NASA-CountDown.zip
- 1F5A9621-NASA-CountDown-1.3.9.1.zip

Meanwhile this mod has only had one recent release, which means there should only be one download:

https://github.com/KSP-CKAN/CKAN-meta/commits/master/NASA-CountDown

That suggests the re-downloading is caused by is mismatched hashes; the Inflator saved to 25B8A610 and/or FA78F3CE (why two?), while the Infra is checking for 1F5A9621?

**Comment by HebaruSan** [comment]
Confirmation:

![image](https://user-images.githubusercontent.com/1559108/73620577-86a8c680-462a-11ea-8283-2cc4be82b49a.png)


![image](https://user-images.githubusercontent.com/1559108/73620557-6d077f00-462a-11ea-9386-91489aff7a23.png)

**Comment by HebaruSan** [comment]
Aha! With spaces:

- https://spacedock.info/mod/1462/NASA CountDown Clock Updated/download/1.3.9.1
- 25b8a610370265cc732bc9bec79c18b11ecc6484 (the hash netkan.exe uses)

With `%20` instead:

- https://spacedock.info/mod/1462/NASA%20CountDown%20Clock%20Updated/download/1.3.9.1
- 1f5a962154a99b18d6dc7da11058454f37c77732 (the hash Infra uses)

So they get different hashes because they're hashing slightly different URLs. 

The SpaceDock API returns the URL with `%20`, and that's what netkan prints to the .ckan file as well:

https://spacedock.info/api/mod/1462

/mod/1462/NASA%20CountDown%20Clock%20Updated/download/1.3.9.1

And that's because `Uri.ToString()` (which [`NetFileCache.CreateURLHash uses to generate the hash](https://github.com/KSP-CKAN/CKAN/blob/204ba8b1216c97adc340032c51d5578edcaaedfe/Core/Net/NetFileCache.cs#L620-L628)) unescapes the spaces!

https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring

```
// Create a new Uri from a string address.
Uri uriAddress = new Uri("HTTP://www.Contoso.com:80/thick%20and%20thin.htm");

// Write the new Uri to the console and note the difference in the two values.
// ToString() gives the canonical version.  OriginalString gives the orginal 
// string that was passed to the constructor.

// The following outputs "http://www.contoso.com/thick and thin.htm".
Console.WriteLine(uriAddress.ToString()); 

// The following outputs "HTTP://www.Contoso.com:80/thick%20and%20thin.htm".
Console.WriteLine(uriAddress.OriginalString);
```

So our Python implementation of `Ckan.cache_prefix` will need to replicate that unescaping behavior.
