### ISSUE TITLE
[Bug] Indexer holding many SSH sessions open

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#142]
Problem
-------
Each run is leaving many defunct ssh processes open, which would suggest that however gitpython is being used, isn't letting go of the process properly.
```
netkan   17747  0.0  0.0      0     0 ?        Z    01:40   0:00 [ssh] <defunct>
netkan   17835  0.0  0.0      0     0 ?        Z    01:40   0:00 [ssh] <defunct>
```
A single run
```
netkan@a43caac9d5dc:~$ ps -waux --sort=start_time|grep "01:"|grep ssh|wc -l
153
```
< 24 hours of uptime
```
netkan@a43caac9d5dc:~$ ps -waux --sort=start_time|grep ssh|wc -l
1699
```
The result is that over time the service starts thrashing the disk and eventually crashes.

![2020-02-04_14-33-40](https://user-images.githubusercontent.com/3467784/73719782-5dd41e80-475b-11ea-8e38-d4a795e12baf.png)

**Comment by HebaruSan** [comment]
We might be able to switch from SSH to HTTPS, by storing the token into `~/.git-credentials` in this format:

```
https://netkan-bot:token@github.com
```

**Comment by techman83** [comment]
Possibly, but I'm not entirely sure it'd fix the problem. It's probably just a side effect of the actual problem. GitPython calls git directly, so all of the git interactions, for better or worse, happen within git itself and are separate to python.

**Comment by HebaruSan** [comment]
Can we figure out which operation those processes were created to perform? Since we have so few new mods indexed per day, I think we can rule out `add`, `commit`, and `push`. Is it just the `pull` in `MessageHandler._update_master`?

Also I wonder if `__exit__` is being called consistently; it's hard to know since it's left to the runtime's handling of `with` blocks. Maybe some garbage collection logic is delaying the clean-up?

https://github.com/KSP-CKAN/NetKAN-Infra/blob/614db33982c1904280bf89fa9053d10998372009/netkan/netkan/indexer.py#L212-L213

**Comment by HebaruSan** [comment]
> I think we can rule out add, commit, and push

Not quite the case; we **do** perform one `push` per batch, after handling the non-staged modules:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/614db33982c1904280bf89fa9053d10998372009/netkan/netkan/indexer.py#L247-L250

In total, each batch of 10 messages looks like it would do:

- Two `pull`s (one in `__enter__` and one in `process_ckans`)
- One `push` (in `process_ckans`)

... regardless of whether any of the modules were changed. We can probably eliminate the `push` (when there are no changes) and one of the `pull`s with some light refactoring. The overall problem would remain but in a less severe form.

**Comment by techman83** [comment]
> OK, reading up on context managers, it sounds like the calling of `__exit__` is pretty strongly guaranteed, so never mind that.

Yeah, context managers are pretty neat. If we were leaning on threads I could see scenarios where we might trip ourselves up, but that isn't the case here.

I have pondered if we are tripping up the abuse mechanisms and stalling the ssh connections. As previously there were significant pauses between batches of 10, but with the Inflator improvements we can really rip through the indexing run.

**Comment by techman83** [comment]
Well. It would appear the issue is identical. Which is interesting.
```
ps waux|grep defunct|wc -l
155
```

**Comment by HebaruSan** [comment]
Apparently related (I didn't find this, @techman83 did):

https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

Apparently git doesn't wait for ssh to finish, which turns it into a zombie process, and containers don't have a mechanism for cleaning them up.

**Comment by HebaruSan** [comment]
Also apparently related: aws/amazon-ecs-agent#852
The `--init` flag runs a zombie reaping process in the container.
(Again credit to @techman83 for finding this)
