### ISSUE TITLE
[Feature] Rewrite Webhooks

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#15]
To get us across the line the existing webhooks have been used. We should switch this out for something like flask.

To Do
-----------
- [ ] Handle GitHub Webhooks
- [ ] Handle Spacedock Webhooks
- [ ] Handle Internet Archive Mirroring

We can probably sort #14 first and look at how we do this. We can likely have a TaskDefinition and a Webhooks Inbound queue or use a temporary Queue (Queues are free, traffic to them isn't, so I don't know the benefit for temporary for this use case, except it's faster and we don't care about having a few extra queues sitting idle). We can also use an archive queue and write a specific task definition for handling those tasks.

**Comment by HebaruSan** [comment]
Might as well attempt #8 if we have to rewrite it all anyway.

**Comment by techman83** [comment]
Even with a brute force full scan of the NetKAN repo, it takes < 100ms to pull out the identifiers. So I reckon we could do this without much hassle.

```python
In [18]: from pathlib import Path 
    ...: import json 
    ...: def test(): 
    ...:     identifiers = [] 
    ...:     for netkan in Path('.').glob('*.netkan'): 
    ...:         identifiers.append(json.loads(netkan.read_text())['identifier']) 
    ...: print(timeit.timeit('test()', globals=globals(), number=100)/100)                                                                                                                                                                                                                                                   
0.08117726542055607
```
