### ISSUE TITLE
Should CKAN-meta-dev be revived or retired?

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#155]
## Background

These repos track pre-release versions of mods:

- https://github.com/KSP-CKAN/NetKAN-dev
- https://github.com/KSP-CKAN/CKAN-meta-dev

Each mod is tracked on a separate git branch:

![image](https://user-images.githubusercontent.com/1559108/76688870-f4ccaa00-6628-11ea-8e0a-e54135b64a53.png)

This file is used by the client to generate default options for adding repositories, so users can opt in to pre-releases for specific mods:

- https://github.com/KSP-CKAN/CKAN-meta/blob/master/repositories.json

Looking at the commit histories, this seems to have been mainly a project of @hakan42.

## Problem

This metadata was last updated in 2015; recent pre-releases are unavailable. But the (now useless) repos are still listed in the client as if they do something. (It looks like this may have been lost with the switch to the original NetKAN-bot code, which has its first commit around this same time.)

The exception is `MechJeb2-dev`, which is hosted on ksp.sarbian.com and contains versions up to the present.

This was pointed out on the Discord by @Poodmund.

## Suggestions

Do we want/intend to still support this? If so, we should figure out how to get these netkans updating again. It would be fairly challenging due to the special use of branches to split up the data; the Infra currently has no equivalent mechanism for that, so it would **not** simply be a matter of setting up another bot instance with alternate URLs for NetKAN and CKAN-meta.

If we don't want this anymore, then we should remove those repos from that `repositories.json` file and add some comments to NetKAN-dev and CKAN-meta-dev explaining what they were and why they're retired.

**Comment by techman83** [comment]
I believe this was partially a Jenkin's thing. It was re-configured in the new infrastructure by one of the earlier maintainers and it broke soon after. No one ever really asked about it, so never really took the time to understand what it was trying to achieve.

**Comment by HebaruSan** [comment]
Jenkins as in it would run when you push a commit as opposed to the bot being scheduled in the background? I may not be following that entirely.

I believe it was trying to achieve an opt-in for pre-release versions for certain mods, so a user could install bleeding edge releases or nightly builds, etc.

Any thoughts on whether to bring this back or not? We are currently in kind of an in-between place now with respect to this. Of this list (Settings &rarr; CKAN Settings &rarr; New button under Metadata Repositories), only default and MechJeb2-dev are useful:

![image](https://user-images.githubusercontent.com/1559108/76819357-d240b980-67ff-11ea-87f5-c44e37050f7b.png)

**Comment by hakan42** [comment]
Hi all,

I was the one who started those multiple repositories for pre-release testing. If the Jenkins jobs building them are gone, I would vote for removing the feature completely. I guess it had only value for build master geeks like myself :)

Regards,
Hakan

**Comment by techman83** [comment]
My memory is pretty good it would seem then :slightly_smiling_face: 
https://ci.ksp-ckan.space/
|Name  | Last Success | Last Failure | Last Duration | 
| -- | -- | -- | -- |
| CKAN-meta | 4 hr 46 min - #1648 | 3 days 4 hr - #1645 | 1 min 29 sec |
| NetKAN | 1 day 15 hr - #9373 | 1 day 16 hr - #9372 | 1 min 28 sec |
| Prerelease_Inflator_-_CaptainsLog | 4 yr 8 mo - #1 | N/A | 0.28 sec |
| Prerelease_Inflator_-_MechJeb2 | 4 yr 8 mo - #1 | N/A | 0.34 sec |
| Prerelease_Inflator_-_SCANSat-dev | 4 yr 8 mo - #1 | N/A | 0.32 sec |

**Comment by HebaruSan** [comment]
Pruned the list:

![image](https://user-images.githubusercontent.com/1559108/77295507-fdcf1280-6cdd-11ea-9774-d2254df94fcf.png)
