### ISSUE TITLE
[Bug] NetKAN webhook is failing

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#157]
The last successful NetKAN webhook was on April 18:

![image](https://user-images.githubusercontent.com/1559108/79814623-41b14800-836e-11ea-87d0-c830a55fe8de.png)

The log reports something with a certificate:

![image](https://user-images.githubusercontent.com/1559108/79814565-1dee0200-836e-11ea-832d-2fe18c6af22d.png)

**Comment by techman83** [comment]
Hmm, I'm guessing the restart schedule doesn't actually work. As the certificates have been updated! Kicked them by hand and have redelivered the hooks. Refer to #158
