### ISSUE TITLE
[Bug] Scheduled Restarts of Webhooks not Restarting

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#158]
Problem
-------
This is supposed to get restarted weekly (shortly after the cert renewal is checked)
```
50c539a33a62        kspckan/webhooks-proxy           "nginx -g 'daemon of…"   2 months ago        Up 2 months             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp
29f80c1275ef        kspckan/netkan                   ".local/bin/gunicorn…"   2 months ago        Up 2 months
```
Certs do get renewed, but 2 months is about when we last did a prod deployment.

**Comment by HebaruSan** [comment]
Looking for other places where we redeploy, the `--service-name` argument is generally passed the name of the service without a `Service` suffix:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/a374d2187f38285e9f6306bc8cb9a99d97794851/bin/push_deploy_containers.sh#L18-L19

https://github.com/KSP-CKAN/NetKAN-Infra/blob/a374d2187f38285e9f6306bc8cb9a99d97794851/bin/push_deploy_containers.sh#L24-L25

https://github.com/KSP-CKAN/NetKAN-Infra/blob/a374d2187f38285e9f6306bc8cb9a99d97794851/bin/push_deploy_containers.sh#L30-L31

https://github.com/KSP-CKAN/NetKAN-Infra/blob/a374d2187f38285e9f6306bc8cb9a99d97794851/bin/push_deploy_containers.sh#L36-L37

https://github.com/KSP-CKAN/CKAN/blob/16994590ee0318d6bb93c90455e1dead093a02cc/build.cake#L88-L90

But in this one case, the `Service` suffix is included:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/a374d2187f38285e9f6306bc8cb9a99d97794851/prod-stack.py#L707-L709

My hypothesis is that somehow this makes it fail to find the service. If correct, then changing the above to simply `Webhooks` should help (and this should probably be done anyway just to be consistent).
