### ISSUE TITLE
[Request for comment] Netkan warnings

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#160]
## Motivation

There are some minor inconsistencies that can arise for a module that need not stop it from indexing but would be nice to know about for maintainer follow-up:

- A .version file is present but no `$vref` is set
- A .cfg file contains ModuleManager syntax but ModuleManager is not a dependency
- Compatible with all future KSP versions and contains a DLL (they **always** break eventually)

There are probably other similar cases of which I haven't yet thought.

## Ideas

It would be trivial to write a `Validator` class in `netkan.exe` that would detect these conditions and use `Log.Warn` to print warnings.

However, `Log.Warn` would only be visible from the command line, which is not the only or even the primary use case of `netkan.exe` these days. It has an alternate identity as the bot's Inflator, in which it inspects **all** modules every day. `Log.Warn` would do nothing for that use case. Instead, the warnings would have to be collected and inserted into a queue message attribute.

The current queue messages use an `ErrorMessage` attribute to transmit fatal errors, but internally the Inflator handles these by throwing and catching exceptions.

## Questions

- How should these non-fatal warnings be passed from the Inflator to the Indexer? It should have the ability to contain multiple messages, because we do not stop processing a module upon raising one of these warnings.
  - Should we re-use the `ErrorMessage` attribute?
  - Should we use a new message attribute?
  - Something else?
- How should they be reported in the status page?
  - Should we re-use the Error column?
  - Should we add a new Warning column?
  - Something else?
- How should the Inflator trigger and collect such warnings internally? It cannot use exceptions because this stops processing of the module. (This is not strictly a NetKAN-Infra topic, but I am including it because it's a key question that needs to be answered to implement this.)

**Comment by techman83** [comment]
> * How should these non-fatal warnings be passed from the Inflator to the Indexer? It should have the ability to contain multiple messages, because we do not stop processing a module upon raising one of these warnings.
>   
>   * Should we re-use the `ErrorMessage` attribute?
>   * Should we use a new message attribute?
>   * Something else?

We should probably avoid re-using this attribute as it's relatively easy to add attributes, but if we overload the attribute it'll make it harder to separate out later if we want to. Especially considering these aren't errors that should cause an inflation not to proceed.

> * How should they be reported in the status page?
>   
>   * Should we re-use the Error column?
>   * Should we add a new Warning column?
>   * Something else?

I think initially it would be ok to re-use the Error column. Maybe rename it Errors/Warnings. If we find that inconvenient we can always change it as it's just presentation. 

> * How should the Inflator trigger and collect such warnings internally? It cannot use exceptions because this stops processing of the module. (This is not strictly a NetKAN-Infra topic, but I am including it because it's a key question that needs to be answered to implement this.)

Good question. I think the further from presentation layer we get, the more we'd probably want to separate out that logic. I'm not super across the internals of how that works in NetKAN though.

**Comment by HebaruSan** [comment]
> We should probably avoid re-using this attribute
> I think initially it would be ok to re-use the Error column

Great, that makes sense to me!

On the third question, it looks like we might be able to use `Log.Warn` after all with an "appender" class, similar to how we send bot errors to Discord:

- https://logging.apache.org/log4net/release/manual/introduction.html

**Comment by techman83** [comment]
Sounds grand!

**Comment by HebaruSan** [comment]
> It would be trivial to write a `Validator` class in `netkan.exe` that would detect these conditions

Partly true. When the `NetkanValidator` runs, we do not yet have the ZIP file; when the `CkanValidator` runs, we no longer have the `$vref`. So some magic will be needed so a validator would have both the ZIP file and the `$vref` at the same time.

**Comment by HebaruSan** [comment]
> I think initially it would be ok to re-use the Error column. Maybe rename it Errors/Warnings.

I meant to ask an intermediate question; should we _store_ the warnings in the `last_error` attribute of the status object, or a new one? We can have the column look to multiple attributes if we need to, so visual sharing of the column could be achieved either way. I kind of think it makes more sense to separate them in the db.

**Comment by techman83** [comment]
I think we should add a new one. But you may have already done that in the PR. Which I'll look at today :slightly_smiling_face:
