### ISSUE TITLE
[Bug] NetKAN inflation webhook is timing out

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#174]
![image](https://user-images.githubusercontent.com/1559108/82937017-10233200-9f55-11ea-8319-bf3f6fab2639.png)

![image](https://user-images.githubusercontent.com/1559108/82937136-3ea10d00-9f55-11ea-860a-255189afaaa2.png)

The successful ones are just rejecting inflation for branches other than master:

![image](https://user-images.githubusercontent.com/1559108/82937467-cf77e880-9f55-11ea-8f21-59be091f9235.png)

So the hook is running and getting past the signature check, etc., but it's timing out sometime later.

**Comment by HebaruSan** [comment]
No exceptions are logged to Discord, strangely. And the Scheduler still seems to be working (when it doesn't skip a pass); in theory that rules out problems with the queues.

**Comment by HebaruSan** [comment]
The latest versions of WarpDrive and Bumblebee are on archive.org, so the CKAN-meta mirrorer hook seems OK.

**Comment by HebaruSan** [comment]
My current best guess is that this line is hanging due to some problem or conflict with the git repos:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/4b5e1d65f66e0209025fef0e5ca1e7c087d9427d/netkan/netkan/webhooks/github_inflate.py#L58

Just about anything else should throw an exception, I think.

**Comment by techman83** [comment]
Might be a gunicorn issue, maybe our worker timeouts aren't generous enough?

```
[2020-05-26 21:35:48 +0000] [613] [INFO] Booting worker with pid: 613
[2020-05-27 02:34:17 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:613)
[2020-05-27 02:34:18 +0000] [628] [INFO] Booting worker with pid: 628
```

**Comment by techman83** [comment]
I actually can't pull the CKAN-meta repo, it just hangs!

**Comment by HebaruSan** [comment]
Maybe we had too many (Indexer-created) commits to pull.

**Comment by techman83** [comment]
Not entirely sure! I haven't sat down long enough to understand the ins and outs of how git uses memory.

**Comment by HebaruSan** [comment]
Well all the error symbols are gone from the webhook log. I guess we're back in business. Thanks!

**Comment by techman83** [comment]
Yeah, I re-fired them off to check. Something we'll need to keep an eye on.
