### ISSUE TITLE
[Feature] Run Indexer more Frequently

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#187]
Problem
-------
The indexer refactor was intended to bring us to a point where we could efficiently index more frequently. 

Mostly what has held us back was to do with Compute resources.  But with hash caching implemented in KSP-CKAN/CKAN#2940 by @HebaruSan and the branching refactor in #178 our cpu/disk io usage is now pretty negligible.

**CPU Usage Credits**
![2020-06-15_15-09-26](https://user-images.githubusercontent.com/3467784/84627905-4d5a5e80-af1a-11ea-8e31-fc9669cfb5c9.png)

**Disk Burst Credits** (6/6 is approximately when the refactor was merged)
![2020-06-15_15-09-55](https://user-images.githubusercontent.com/3467784/84627903-4c293180-af1a-11ea-916f-521dbe9d00f5.png)

Considerations
-------
A regular non-webhooks pass currently takes around 10-11 minutes to complete. This is a drastic improvement over even the earlier indexing runs with less than half the number of mods! :tada: 

We currently consume around 600-700 thousand SQS messages a month, which is well within the free tier and even doubling that usage would cost very little.

The main thing we'd need to watch out for is our github api limits, which appears to be around 1400 calls per non-webhooks pass. 
```json
{
  "resources": {
    "core": {
      "limit": 5000,
      "remaining": 3647,
      "reset": 1592200613
    },
    "search": {
      "limit": 30,
      "remaining": 30,
      "reset": 1592200323
    },
    "graphql": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1592203863
    },
    "integration_manifest": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1592203863
    },
    "source_import": {
      "limit": 100,
      "remaining": 100,
      "reset": 1592200323
    }
  },
  "rate": {
    "limit": 5000,
    "remaining": 3647,
    "reset": 1592200613
  }
}
```
Suggestions
-----------
We should bump up the non-webhooks pass to every 30 minutes (currently every 2 hours). Comments/Thoughts?

**Comment by HebaruSan** [comment]
Sounds good, I was kind of expecting this to be a PR. :)

One thought, we do still take up quite a lot of CPU on the first pass after merging code changes, as all the hashes have to be recomputed (which also drags it out to a couple of hours). I was thinking we could try caching them on disk to help with that, so for example the cache dir might contain:

- FFA1EF94-ContractsWindowPlus-9.4.zip
- FFA1EF94-ContractsWindowPlus-9.4.zip.sha1
- FFA1EF94-ContractsWindowPlus-9.4.zip.sha256

The storage impact should be negligible, about 105 more bytes per cached ZIP. This should get the first pass after a merge up to a quick speed. Should we do this first?

**Comment by techman83** [comment]
Hahaha, I thought about it! Good work in KSP-CKAN/CKAN#3080! We may need to check we're cleaning up those files in our regular purge.
