### ISSUE TITLE
[Feature] NetKAN Staging Reason

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#19]
The staging reason didn't make it across to the new code.

To rectify this, the Inflator will need to set an attribute containing the reason if there is one. Then the indexer can use `getattr(self, 'StagingReason', 'Default Description Here')` to set it.

**Comment by HebaruSan** [comment]
Should already be covered on the Inflator side:

https://github.com/KSP-CKAN/CKAN/blob/910d89b33f80dc3b8a8c17f39ed8e81f6b867582/Netkan/Processors/QueueHandler.cs#L160-L170

**Comment by techman83** [comment]
Ohhh! Easy, then it'll be a one liner for the indexer 🎉
