### ISSUE TITLE
[Bug] Cache cleaner task doesn't clean the cache

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#217]
## Background

The `clean-cache` task is supposed to purge files 30 days old or older from the cache, once per day.

https://github.com/KSP-CKAN/NetKAN-Infra/blob/89b7d827cccf03e1810992fd91444d5b58de4011/prod-stack.py#L730-L741

https://github.com/KSP-CKAN/NetKAN-Infra/blob/89b7d827cccf03e1810992fd91444d5b58de4011/netkan/netkan/cli/utilities.py#L151-L170

## Problem

That does not seem to happen to any significant extent. We currently have many files in the cache that are 60+ days old:

http://status.ksp-ckan.space/

![image](https://user-images.githubusercontent.com/1559108/112771814-34401b80-901d-11eb-9553-16f0e8d2b964.png)

This may put us at increased risk of running out of resources.

**Comment by HebaruSan** [comment]
Having audited it closely and probed most of it in an interactive Python session, I am pretty confident that the Python code here is fine. The expressions generate the correct values as you would expect, and the loop and checks and deletion calls are as they should be. I'm starting to suspect the mapping from the shared cache folder into the container, admittedly partly because I can't validate that aspect to the same degree.

Then again, we certainly have mods that haven't been updated in much longer than 60 days, so the fact that there's a shorter limit in the list is quite odd, and may suggest that the job might still be running and deleting things, just not as we'd expect. If the job wasn't doing anything at all, then the oldest entries in the cache should be nearly as old as when the new infra was created rather than just 65 days.

It would be interesting to know whether we _ever_ see a `Purging X from ckan cache` message in the log.

**Comment by HebaruSan** [comment]
Very speculatively, this is a generator:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/89b7d827cccf03e1810992fd91444d5b58de4011/netkan/netkan/cli/utilities.py#L165

And this removes an entry from the sequence it generates (in concrete terms of contents of the disk if not necessarily in terms of how the Python primitives work):

https://github.com/KSP-CKAN/NetKAN-Infra/blob/89b7d827cccf03e1810992fd91444d5b58de4011/netkan/netkan/cli/utilities.py#L170

_Maybe_ after removing one file, the generator is invalidated and the task bails?
Or maybe the generator is technically still valid but no longer knows how to find the next file, so the loop ends as if it had finished?

If this or something like it was the cause, then the task would delete one old file, probably in an unpredictable order. So we would have many too-old files hanging around, but they would still slowly go away over time. That's essentially what we have.

**Comment by techman83** [comment]
Let me check that the task is actually running. It's generally lists that get a bit wonky if you mess with them while iterating over them. This is also a pretty common example pattern for the glob generator.

I'll check the scheduled task, I'd suspect something at an infra level over something at this level. 

(thanks for opening the issue, I've been meaning to for a while)

**Comment by techman83** [comment]
Well this doesn't fill me with confidence
![2021-03-29_08-26-23](https://user-images.githubusercontent.com/3467784/112773393-8195aa80-9068-11eb-835a-d22c434da802.png)

Probably some permissions issue. That I likely fixed when we rolled it out and then got blown away with a future update. I'll dig into it later today.

**Comment by techman83** [comment]
Launching the task manually shows it works from a code perspective, so likely an obscure permission :-/

```
[ec2-user@ip-172-31-18-233 ~]$ docker logs -f 38e0a0314a6d
Checking cache for files older than 30 days
Purging 5C4FD830-netkan-WaterfallRestock.zip from ckan cache
Purging EA33F40C-netkan-Heracleitus.zip.sha256 from ckan cache
Purging E56C0F11-netkan-CommunityPartsTitlesExtrasCategory.zip.sha256 from ckan cache
Purging 02FE2D4B-netkan-SemiSaturatableRW.zip.sha1 from ckan cache
Purging 3C1AA629-netkan-CryoEngines.zip.sha1 from ckan cache
Purging 117362DE-netkan-SpaceTuxLibrary.zip.sha1 from ckan cache
Purging 2C7BC042-netkan-ContractConfigurator-KerbinSpaceStation.zip.sha256 from ckan cache
Purging AB8B0DFB-netkan-Blueshift.zip from ckan cache
Purging EA33F40C-netkan-Heracleitus.zip from ckan cache
Purging B6A9BB16-netkan-TestLite.zip from ckan cache
Purging F910C6EF-netkan-JanitorsCloset.zip.sha256 from ckan cache
Purging DB0F5CDD-netkan-JanitorsCloset.zip.sha1 from ckan cache
Purging 0FA70685-netkan-Waterfall.zip.sha1 from ckan cache
Purging 5A61743D-netkan-PayToPlay.zip.sha256 from ckan cache
Purging F910C6EF-netkan-JanitorsCloset.zip.sha1 from ckan cache
Purging A09A9D20-netkan-NeptuneCamera.zip from ckan cache
Purging DB0F5CDD-netkan-JanitorsCloset.zip.sha256 from ckan cache
Purging 393D8429-netkan-KSPInterstellarExtended.zip.sha1 from ckan cache
Purging 94D6C7AB-netkan-BDArmoryForRunwayProject.zip.sha256 from ckan cache
Purging B6A9BB16-netkan-TestLite.zip.sha1 from ckan cache
Purging 2C7BC042-netkan-ContractConfigurator-KerbinSpaceStation.zip from ckan cache
Purging 59448BD4-netkan-FarFutureTechnologies.zip from ckan cache
Purging 117362DE-netkan-SpaceTuxLibrary.zip from ckan cache
Purging 9CD90EB3-netkan-KSPInterstellarExtended.zip from ckan cache
Purging A09A9D20-netkan-NeptuneCamera.zip.sha1 from ckan cache
Purging 9CD90EB3-netkan-KSPInterstellarExtended.zip.sha1 from ckan cache
Purging 5A61743D-netkan-PayToPlay.zip from ckan cache
Purging 3C1AA629-netkan-CryoEngines.zip.sha256 from ckan cache
Purging 02FE2D4B-netkan-SemiSaturatableRW.zip from ckan cache
Purging F62FB6EA-netkan-Corelian.zip.sha256 from ckan cache
Purging E56C0F11-netkan-CommunityPartsTitlesExtrasCategory.zip.sha1 from ckan cache
Purging AB8B0DFB-netkan-Blueshift.zip.sha1 from ckan cache
Purging 94D6C7AB-netkan-BDArmoryForRunwayProject.zip.sha1 from ckan cache
Purging 393D8429-netkan-KSPInterstellarExtended.zip from ckan cache
Purging F62FB6EA-netkan-Corelian.zip from ckan cache
Purging A09A9D20-netkan-NeptuneCamera.zip.sha256 from ckan cache
Purging 9CD90EB3-netkan-KSPInterstellarExtended.zip.sha256 from ckan cache
Purging AB8B0DFB-netkan-Blueshift.zip.sha256 from ckan cache
Purging 5C4FD830-netkan-WaterfallRestock.zip.sha1 from ckan cache
Purging EA33F40C-netkan-Heracleitus.zip.sha1 from ckan cache
Purging F910C6EF-netkan-JanitorsCloset.zip from ckan cache
Purging 2C7BC042-netkan-ContractConfigurator-KerbinSpaceStation.zip.sha1 from ckan cache
Purging 59448BD4-netkan-FarFutureTechnologies.zip.sha256 from ckan cache
Purging ECD8F949-netkan-BDArmoryForRunwayProject.zip from ckan cache
Purging 393D8429-netkan-KSPInterstellarExtended.zip.sha256 from ckan cache
Purging ECD8F949-netkan-BDArmoryForRunwayProject.zip.sha256 from ckan cache
Purging 3C1AA629-netkan-CryoEngines.zip from ckan cache
Purging F62FB6EA-netkan-Corelian.zip.sha1 from ckan cache
Purging 59448BD4-netkan-FarFutureTechnologies.zip.sha1 from ckan cache
Purging 0FA70685-netkan-Waterfall.zip from ckan cache
Purging 5A61743D-netkan-PayToPlay.zip.sha1 from ckan cache
Purging DB0F5CDD-netkan-JanitorsCloset.zip from ckan cache
Purging 5C4FD830-netkan-WaterfallRestock.zip.sha256 from ckan cache
Purging 0FA70685-netkan-Waterfall.zip.sha256 from ckan cache
Purging 02FE2D4B-netkan-SemiSaturatableRW.zip.sha256 from ckan cache
Purging E56C0F11-netkan-CommunityPartsTitlesExtrasCategory.zip from ckan cache
Purging 117362DE-netkan-SpaceTuxLibrary.zip.sha256 from ckan cache
Purging ECD8F949-netkan-BDArmoryForRunwayProject.zip.sha1 from ckan cache
Purging 94D6C7AB-netkan-BDArmoryForRunwayProject.zip from ckan cache
Purging B6A9BB16-netkan-TestLite.zip.sha256 from ckan cache
```
