### ISSUE TITLE
SpaceDock IP whitelisting is out of date

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#277]
SpaceDock moved to new servers about two weeks ago, and its IP addresses changed. Since the NetKAN web hooks use IP whitelisting to block undesired traffic, this means SpaceDock is no longer whitelisted, and we no longer receive automatic pull requests for indexing mods or update notifications.

I don't know what's involved in updating this, but if it can be deduced from the site, here's a link:

https://spacedock.info/

**Comment by techman83** [comment]
Done!
