### ISSUE TITLE
Staging branches created unnecessarily

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#32]
## Problem

We seem to be getting a lot of weird new branches:

![image](https://user-images.githubusercontent.com/1559108/65188593-4cb19c00-da5e-11e9-8871-ed0c5a44c2c1.png)

It looks like we're creating them for staged modules, even if they don't have updates?

**Comment by techman83** [comment]
Hahaha That's an amusing, but benign bug! That's exactly what's happening, probably should add a check to see if we actually committed something before pushing.

I did change the design a little, the former staging was stupid complex and wasn't used the way I envisioned. So I simplified it a lot! So the branch names are now the mod identifier to avoid all the Cherry picking we had to do before.
