### ISSUE TITLE
[Feature] Distinguish containers in .gitconfig user name

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#38]
Problem
-------

While investigating #33 and #36, it's hard to tell which commits are from the Indexer, which from the web hooks, and which from the download counter. The author is always just `NetKAN inflator Robot` regardless of the container of origin.

Suggestions
-----------
**Describe the solution you'd like**

Make this name container-specific:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/e5735d36af05ecfd442ba075aae2b83d6f95911e/netkan/.gitconfig#L1-L3

Suggestions:

- NetKAN Robotic Indexer
- NetKAN Robotic Download Counter
- NetKAN Web Hook

Then the git history would tell us who did what more clearly.

**Comment by techman83** [comment]
We could, though I expect in the fullness of time the Indexer itself will take charge of all the commits. It can basically consume any changes faster than anything else producing them, so changes are always going to be near real time. It will reduce the amount of merge commits and any fights over who does what.

The Download Counter could submit them too, but currently the indexer assumes a ckan.
