### ISSUE TITLE
[Feature] Send bot errors to Discord

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#52]
CKAN's Discord has channels for notifications from GitHub and Travis. It would be awesome if errors from the new Infra code could be sent to a new channel there as well. Ideally this would include both inflation errors for specific modules and exceptions thrown by other components.

~~There's a `discord.py` module that could probably be used to do this.~~
Apparently that module targets a more interactive/reactive use case (and has great difficulty with simply dumping messages):
https://github.com/Rapptz/discord.py/issues/2391#issuecomment-546164552

**Comment by HebaruSan** [comment]
If/when the channel is created, suggest letting members of the developer group reply there to allow discussion of particular errors.

**Comment by DasSkelett** [comment]
I'm gonna link my own alert script here, that I'm running on my PC, somebody implementing this can use this as an inspirational starting point if he wants to.
Nothing magic, but still...

! Warning, not suited for production usage as is !
https://gist.github.com/DasSkelett/fb1065020942cf952478ee6f9c0d5257

**Comment by techman83** [comment]
That's a super neat idea! Could probably use Cloudwatch to grab non zero container exits and push them at discord.

The indexing errors will get super noisy and will likely lead to things getting missed. But we could check if the error changed, we have ready access to the status object.
