### ISSUE TITLE
[Feature] Write a documentation

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/NetKAN-Infra#54]
Problem
-------
**Is your feature request related to a problem? Please describe.**
We have no documentation for this new architecture.
The Wiki of KSP-CKAN/CKAN is outdated (especially the https://github.com/KSP-CKAN/CKAN/wiki/How-does-CKAN-work page), and while most of how this works is described in https://github.com/KSP-CKAN/CKAN/pull/2798, the infos are scattered around multiple PRs and issues and the code itself.

Suggestions
-----------
**Describe the solution you'd like**
Write a documentation. Probably best to either add a new page in the wiki of KSP-CKAN/CKAN, or use the one linked above.

A brain dump of what should be documented (not complete):
* **Theory of operation**: We are using a microservice approach
* That those microservices communicate via the AWS SQS system with each other
	* What are those queues, how are the messages set up (attributes, payload...)?
	* How to interact with it?
* What part of the infrastructure is where?
	* The inflator in the netkan.exe, the indexer here in ./netkan/netkan/indexer.py, the scheduler here, the status page in NetKAN-status 
* How to set up a local development environment
	* What env vars should be set to what for testing?
	* When using an IDE that wants the dependencies installed locally, how to install them? -> venv
* Usecases of the different webhooks
	* How to trigger them, how are they secured
* And probably much more

**Comment by HebaruSan** [comment]
Or https://github.com/KSP-CKAN/NetKAN-Infra/wiki

**Comment by techman83** [comment]
I think it should go in the README.md and I absolutely agree that we need developer doco. One of the big goals of the project was to make it more accessible for contributors. Microservices and Automated Build/Deploy was a big part of that, along with simplification of the code. The former project was thorough, but suffered from being a big and hard to understand monolith.

**Comment by HebaruSan** [comment]
Agreed, the README has two huge advantages:

- It's the first thing you see when you visit the repo on GitHub; and
- We can make documentation updates in the same PR as the code changes that necessitate them

**Comment by HebaruSan** [comment]
I just learned this term. Might be nice to include:
https://en.wikipedia.org/wiki/Theory_of_operation

**Comment by techman83** [comment]
Yes, absoultely. That might be the first thing I write. Because the design and philosophy is very much something that exists in my mind right now and needs to be something that we all can be across. Along with being able to make improvements to it.

**Comment by HebaruSan** [comment]
Did #76 fix this with its README additions?

**Comment by DasSkelett** [comment]
It's a good start, ee can close this issue. Just remember to keep the README updated ;)
