### ISSUE TITLE
Frozen modules no longer drop off the status list

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#60]
Problem
-------

These mods have been frozen, but they still appear on the status page:

![image](https://user-images.githubusercontent.com/1559108/67308321-85122300-f4bf-11e9-983f-a4cb6b85b193.png)

Since they are no longer being crawled, they will appear to have a problem indefinitely, even though corrective action has been taken (freezing them).

In the legacy infrastructure, modules without a live .netkan file were removed from the status page. We may want to find a way to do that again.

**Comment by techman83** [comment]
It might handy to keep them in the list, but maybe a webhook that clears the last error when a frozen mod is in the list and we can clean up the existing ones by hand (or write a task to do it).

**Comment by DasSkelett** [comment]
If we keep them in the status list, they should be at least marked differently (dark/grey background?).
I see a reason in keeping them in the list (to know which identifiers are taken, to quickly access the netkan file), but they should be distinguishable from active netkans.
