### ISSUE TITLE
[Bug] Same module can't be queued multiple times within 5 minutes 

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#80]
## Problem

@linuxgurugamer uploaded DeployableBatteries 0.1.0.5, which was indexed, and then within 2 minutes he uploaded 0.2.0.5, which was not. See the second half of KSP-CKAN/NetKAN#7481.

## Cause

We use the MD5 of the netkan file contents as the deduplication id for the queue. Since this is always the same unless the netkan is edited, repeated inflation requests within 5 minutes are suppressed.

https://github.com/KSP-CKAN/NetKAN-Infra/blob/39a237ca9cc39dcd860249d214a2e5edaea79fe5/netkan/netkan/metadata.py#L60-L66

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html

> If a message with a particular message deduplication ID is sent successfully, any messages sent with the same message deduplication ID are accepted successfully but aren't delivered during the 5-minute deduplication interval.

**Comment by techman83** [comment]
I think it would be acceptable for us to use a UUID here (python has one in stdlib). It's to avoid retries that succeed and the response not being received appearing as duplicates.

**Comment by linuxgurugamer** [comment]
Has this been implemented, if not, when?

**Comment by techman83** [comment]
NetKAN-Infra is all CI/CD driven now. Beyond infrastructure changes, code changes are deployed as soon as the build completes.
