### ISSUE TITLE
[Bug] Webhooks fail to start under gunicorn 20.0.0

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#85]
Background
----------
After releasing the latest batch of changes the webhooks failed to start. Not being part of the python code, rather gunicorn it didn't send the logs to discord.

Worked around it by locking below 20.0.0 for now.

Problem
-------
```bash
netkan@bef8cb5997ae:~/workspace$ gunicorn -b 0.0.0.0:5000 --access-logfile - "netkan.webhooks:create_app()"
[2019-11-11 03:31:32 +0000] [239] [INFO] Starting gunicorn 20.0.0
[2019-11-11 03:31:32 +0000] [239] [INFO] Listening at: http://0.0.0.0:5000 (239)
[2019-11-11 03:31:32 +0000] [239] [INFO] Using worker: sync
[2019-11-11 03:31:32 +0000] [243] [INFO] Booting worker with pid: 243
Failed to find application object 'create_app()' in 'netkan.webhooks'
[2019-11-11 03:31:33 +0000] [243] [INFO] Worker exiting (pid: 243)
[2019-11-11 03:31:33 +0000] [239] [INFO] Shutting down: Master
[2019-11-11 03:31:33 +0000] [239] [INFO] Reason: App failed to load.
```

**Comment by HebaruSan** [comment]
Huh. See benoitc/gunicorn#2159. Apparently app factories are just broken in that release.

**Comment by techman83** [comment]
Well that'll explain it. Wonder if it's intentional.

**Comment by techman83** [comment]
Looks to be a consequence of moving to using importlib as using `__import__` directly is discouraged.

**Comment by HebaruSan** [comment]
The Gunicorn and Flask devs are now chatting on that issue, and various users are weighing in with their perspectives. Sounds like they're leaning toward restoring the functionality but with a better implementation.

The reason I used the app factory pattern here has been mentioned by others in that discussion: running the tests loads all modules to find tests. When I tried a global variable `app = Flask(__name__)`, tests would fail unless all the webhook `os.environ` context was set.

**Comment by techman83** [comment]
I think the use of the factory pattern is appropriate here and it is configured as per the flask documentation. We can either keep it pinned to 19.9.x until they decide how they're going to sort this going forward. All the right people are talking about it, so it's no real biggie and we're not chomping to use anything in 20.x.x to my knowledge. Alternatively, we're not passing anything to the create app, so we could alter the launch slightly as per [this comment](https://github.com/benoitc/gunicorn/issues/2159#issuecomment-552237957). Personally I think pinning the version is appropriate in the interim.

**Comment by HebaruSan** [comment]
Gunicorn 20.0.3 is out, and it works as far as I can tell.

**Comment by techman83** [comment]
Awesome. We can unpin it at some point :slightly_smiling_face:
