### ISSUE TITLE
[Feature] Purge a specified file from the cache

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#9]
This is an outgrowth of https://github.com/KSP-CKAN/CKAN/issues/2789#issuecomment-507062552. I assume that the initial functionality of the queue-based bot will be identical to NetKAN-bot, so ideas for further improvements should be submitted here for better tracking.

## Motivation

When a mod author uploads a release, waits for the NetKAN-bot to index it, then deletes it and replaces it with a different file at the same URL, CKAN will report file size and hash mismatches when attempting to install. The NetKAN-bot is none the wiser and will happily treat its cached download of the original file as if it was current. If we try to fix the data in CKAN-meta, the bot will overwrite it. The only way to resolve the situation is to manually purge that file from the bot's cache.

(There are exceptions. Mods on GitHub can be handled thanks to its API's timestmaps, see KSP-CKAN/CKAN#2337. I have an attempt ongoing to do the same for SpaceDock, see KSP-SpaceDock/SpaceDock#195.)

## Suggestion

It would be handy if we had an easier way to accomplish this purging. For example, a web page somewhere that allows us to type a filename to delete.

### Discord

A better idea might be to write a bot that would monitor the CKAN Discord and respond to this and other commands:

- `purge` - Delete a cached file by filename, hash, or download URL
- `inflate` - Queue a mod for inflation by identifier
- `inflate_group` - Queue mods for inflation by param `all`, `webhooks`, or `nonhooks` a la #79
- `redeploy` - Run a `redeploy_service` command to restart part of the infrastructure
- `export_status` - Force a dump of the status to the web site JSON

This would represent a more mainstream usage of `python.js` than #68, which is write-only rather than interactive.

**Comment by HebaruSan** [comment]
KSP-SpaceDock/SpaceDock#195 and KSP-CKAN/CKAN#2859 are now live and make the purge part of this mostly unnecessary, since both GitHub and SpaceDock hosted files will now automatically re-download if replaced. There might still be some benefit in writing a Discord bot, but it's not a pressing need at this point.

**Comment by techman83** [comment]
Agreed. I think we're pretty covered by the automation now. Excellent work!
